[project]
requires-python = ">=3.7"

authors = [
  {name = "", email = "pradyun@example.com"},
]
maintainers = [
  {name = "Brett Cannon", email = "brett@example.com"}
]
description = "Lovely Spam! Wonderful Spam!"
readme = "README.txt"